-- Bảng giao hàng (phiếu giao theo xe / khách / sản phẩm)
-- Chạy trong Supabase SQL Editor (DB chính he-thong). An toàn khi chạy lại.

create table if not exists public.giao_hang (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.giao_hang
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists ngay date not null default current_date,
  add column if not exists bsx text,
  add column if not exists so_phieu text,
  add column if not exists tt integer,
  add column if not exists ma_kh text,
  add column if not exists dia_chi text,
  add column if not exists sdt_kh text,
  add column if not exists nvql text,
  add column if not exists ma_san_pham text,
  add column if not exists ten_san_pham text,
  add column if not exists sl numeric(18, 3) not null default 0,
  add column if not exists gia_ban numeric(18, 2) not null default 0,
  add column if not exists thanh_toan text,
  add column if not exists tong_gia_tri numeric(18, 2) not null default 0,
  add column if not exists ghi_chu text;

create index if not exists giao_hang_ngay_idx
  on public.giao_hang (ngay desc);

create index if not exists giao_hang_so_phieu_idx
  on public.giao_hang (so_phieu);

create index if not exists giao_hang_bsx_idx
  on public.giao_hang (bsx);

create index if not exists giao_hang_ma_kh_idx
  on public.giao_hang (ma_kh);

create index if not exists giao_hang_ma_san_pham_idx
  on public.giao_hang (ma_san_pham);

alter table public.giao_hang enable row level security;

drop policy if exists "giao_hang_select_all" on public.giao_hang;
create policy "giao_hang_select_all" on public.giao_hang for select using (true);

drop policy if exists "giao_hang_insert_all" on public.giao_hang;
create policy "giao_hang_insert_all" on public.giao_hang for insert with check (true);

drop policy if exists "giao_hang_update_all" on public.giao_hang;
create policy "giao_hang_update_all" on public.giao_hang for update using (true) with check (true);

drop policy if exists "giao_hang_delete_all" on public.giao_hang;
create policy "giao_hang_delete_all" on public.giao_hang for delete using (true);

comment on table public.giao_hang is 'Phieu giao hang: ngay, BSX, so phieu, khach hang, san pham, gia tri.';
comment on column public.giao_hang.ngay is 'Ngay giao hang';
comment on column public.giao_hang.bsx is 'Bien so xe';
comment on column public.giao_hang.so_phieu is 'So phieu giao';
comment on column public.giao_hang.tt is 'Thu tu dong';
comment on column public.giao_hang.ma_kh is 'Ma khach hang';
comment on column public.giao_hang.sdt_kh is 'So dien thoai khach hang';
comment on column public.giao_hang.nvql is 'Nhan vien quan ly';
comment on column public.giao_hang.sl is 'So luong';
comment on column public.giao_hang.gia_ban is 'Gia ban';
comment on column public.giao_hang.thanh_toan is 'Hinh thuc / trang thai thanh toan';
comment on column public.giao_hang.tong_gia_tri is 'Tong gia tri dong';
