-- Các cột liên kết báo cáo đã có trong supabase-db-kho.sql:
-- nhap_kho.id_bao_cao_nghiem_thu và xuat_kho.id_bao_cao_nghiem_thu.
-- Khi thủ kho lưu phiếu, API ghi id_bao_cao_nghiem_thu vào nhap_kho.
