-- Phiếu bán hàng (Kinh doanh) — nội dung có thể lấy từ lệnh xuất hàng
create table if not exists public.phieu_ban_hang (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ma_phieu text not null,
  ngay_ban date not null default current_date,
  ma_lenh_xuat text,
  ma_khach_hang text,
  ten_khach_hang text not null,
  dia_chi text,
  so_dien_thoai text,
  thanh_toan text,
  nhan_vien text,
  trang_thai text not null default 'Nháp',
  ghi_chu text,
  chi_tiet jsonb not null default '[]'::jsonb
);

create unique index if not exists phieu_ban_hang_ma_phieu_uidx
  on public.phieu_ban_hang (ma_phieu);

create index if not exists phieu_ban_hang_ngay_idx
  on public.phieu_ban_hang (ngay_ban desc);

create index if not exists phieu_ban_hang_khach_idx
  on public.phieu_ban_hang (ten_khach_hang);

create index if not exists phieu_ban_hang_lenh_idx
  on public.phieu_ban_hang (ma_lenh_xuat);

alter table public.phieu_ban_hang enable row level security;

drop policy if exists "phieu_ban_hang_select_all" on public.phieu_ban_hang;
create policy "phieu_ban_hang_select_all" on public.phieu_ban_hang for select using (true);

drop policy if exists "phieu_ban_hang_insert_all" on public.phieu_ban_hang;
create policy "phieu_ban_hang_insert_all" on public.phieu_ban_hang for insert with check (true);

drop policy if exists "phieu_ban_hang_update_all" on public.phieu_ban_hang;
create policy "phieu_ban_hang_update_all" on public.phieu_ban_hang for update using (true) with check (true);

drop policy if exists "phieu_ban_hang_delete_all" on public.phieu_ban_hang;
create policy "phieu_ban_hang_delete_all" on public.phieu_ban_hang for delete using (true);
