-- Bảng khách hàng /khach-hang — tạo bảng + cột bổ sung (an toàn khi chạy lại)

create table if not exists public.khach_hang (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ma_khach_hang text,
  ten_khach_hang text not null,
  dia_chi text,
  dia_chi_moi text,
  cong_no numeric(18,2) not null default 0,
  ma_so_thue text,
  dien_thoai text,
  dt_di_dong_nlh text,
  la_doi_tuong_noi_bo boolean not null default false,
  don_vi_quan_ly text,
  ghi_chu text
);

alter table public.khach_hang
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ma_khach_hang text,
  add column if not exists ten_khach_hang text,
  add column if not exists dia_chi text,
  add column if not exists dia_chi_moi text,
  add column if not exists cong_no numeric(18,2) not null default 0,
  add column if not exists ma_so_thue text,
  add column if not exists dien_thoai text,
  add column if not exists dt_di_dong_nlh text,
  add column if not exists la_doi_tuong_noi_bo boolean not null default false,
  add column if not exists don_vi_quan_ly text,
  add column if not exists ghi_chu text;

create unique index if not exists khach_hang_ma_khach_hang_uidx
  on public.khach_hang (ma_khach_hang)
  where ma_khach_hang is not null and trim(ma_khach_hang) <> '';

create index if not exists khach_hang_created_at_idx
  on public.khach_hang (created_at desc);

create index if not exists khach_hang_ten_idx
  on public.khach_hang (ten_khach_hang);

alter table public.khach_hang enable row level security;

drop policy if exists "khach_hang_select_all" on public.khach_hang;
create policy "khach_hang_select_all"
  on public.khach_hang for select using (true);

drop policy if exists "khach_hang_insert_all" on public.khach_hang;
create policy "khach_hang_insert_all"
  on public.khach_hang for insert with check (true);

drop policy if exists "khach_hang_update_all" on public.khach_hang;
create policy "khach_hang_update_all"
  on public.khach_hang for update using (true) with check (true);

drop policy if exists "khach_hang_delete_all" on public.khach_hang;
create policy "khach_hang_delete_all"
  on public.khach_hang for delete using (true);

comment on table public.khach_hang is 'Danh muc khach hang.';
comment on column public.khach_hang.cong_no is 'Công nợ hiện tại của khách hàng.';
comment on column public.khach_hang.ma_so_thue is 'Mã số thuế hoặc CCCD chủ hộ.';
comment on column public.khach_hang.dt_di_dong_nlh is 'Điện thoại di động của người liên hệ.';
comment on column public.khach_hang.la_doi_tuong_noi_bo is 'Khách hàng có phải đối tượng nội bộ hay không.';
comment on column public.khach_hang.don_vi_quan_ly is 'Đơn vị/chi nhánh quản lý khách hàng.';
comment on column public.khach_hang.ghi_chu is 'Ghi chú bổ sung về khách hàng.';
comment on column public.khach_hang.dia_chi_moi
  is 'Địa chỉ mới của khách hàng; dia_chi lưu địa chỉ cũ.';
