-- =============================================================================
-- DB KIỂM KHO (project riêng — SUPABASE_KIEM_KHO_*)
-- =============================================================================
-- Lỗi trên máy: «Bảng kiem_kho chưa có trên Supabase mới lẫn cũ.»
-- → Chưa chạy SQL tạo bảng trên project kiểm kho (hoặc chưa cấu hình .env).
--
-- Cách chạy:
--   1. Mở Supabase project KIỂM KHO (ref trong .env: SUPABASE_KIEM_KHO_URL)
--      VD hiện tại: https://supabase.com/dashboard/project/yyddiuaankcrqfgbzusf/sql/new
--   2. SQL Editor → New query → dán TOÀN BỘ file này → Run
--   3. Trong Vercel / .env:
--        SUPABASE_KIEM_KHO_URL=...
--        SUPABASE_KIEM_KHO_SERVICE_KEY=...
--        SUPABASE_KIEM_KHO_TABLE=kiem_kho
--        SUPABASE_KIEM_KHO_TONG_HOP_TABLE=kiem_kho_tong_hop
--   4. Redeploy app (hoặc restart server local) rồi F5 máy Keyence
--
-- File gộp từ:
--   supabase-kiem-kho.sql
--   supabase-kiem-kho-tong-hop.sql
--   supabase-kiem-kho-tong-hop-rpc.sql
--   supabase-kiem-kho-chenh-lech-xu-ly.sql
-- =============================================================================

-- Báº£ng kiá»ƒm kho â€” DB phiáº¿u cÃ¢n (njdlkyxdieefeebcyaov)
-- Cháº¡y an toÃ n trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/njdlkyxdieefeebcyaov/sql/new

create table if not exists public.kiem_kho (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ten_kho text,
  dot_kiem_kho text,
  ma_nvl text,
  ma_sp text,
  ten_sp text,
  loai_sp text,
  ngay_gio_kiem_kho timestamptz not null default now(),
  nguoi_kiem_kho text,
  thoi_gian_xac_nhan timestamptz
);

alter table public.kiem_kho
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ten_kho text,
  add column if not exists dot_kiem_kho text,
  add column if not exists ma_nvl text,
  add column if not exists ma_sp text,
  add column if not exists ten_sp text,
  add column if not exists loai_sp text,
  add column if not exists ngay_gio_kiem_kho timestamptz not null default now(),
  add column if not exists nguoi_kiem_kho text,
  add column if not exists thoi_gian_xac_nhan timestamptz;

-- ÄÃ£ bá» tÃ­nh nÄƒng Ä‘á»“ng bá»™ tá»“n Ä‘áº§u ká»³ tá»« kiá»ƒm kho â€” dá»n cá»™t cÅ© náº¿u DB Ä‘Ã£ cÃ³.
alter table public.kiem_kho
  drop column if exists da_dong_bo,
  drop column if exists dong_bo_luc;

create index if not exists kiem_kho_ngay_gio_idx on public.kiem_kho (ngay_gio_kiem_kho desc);
create index if not exists kiem_kho_ma_sp_idx on public.kiem_kho (ma_sp);
create index if not exists kiem_kho_ma_nvl_idx on public.kiem_kho (ma_nvl);
create index if not exists kiem_kho_ten_kho_idx on public.kiem_kho (ten_kho);
create index if not exists kiem_kho_dot_kiem_kho_idx on public.kiem_kho (dot_kiem_kho);
create index if not exists kiem_kho_xac_nhan_idx on public.kiem_kho (dot_kiem_kho, thoi_gian_xac_nhan);

alter table public.kiem_kho enable row level security;

drop policy if exists "kiem_kho_select_all" on public.kiem_kho;
create policy "kiem_kho_select_all"
  on public.kiem_kho for select
  using (true);

drop policy if exists "kiem_kho_insert_all" on public.kiem_kho;
create policy "kiem_kho_insert_all"
  on public.kiem_kho for insert
  with check (true);

drop policy if exists "kiem_kho_update_all" on public.kiem_kho;
create policy "kiem_kho_update_all"
  on public.kiem_kho for update
  using (true)
  with check (true);

drop policy if exists "kiem_kho_delete_all" on public.kiem_kho;
create policy "kiem_kho_delete_all"
  on public.kiem_kho for delete
  using (true);

grant select, insert, update, delete on table public.kiem_kho to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.kiem_kho is 'Phieu / dong kiem kho.';
comment on column public.kiem_kho.ten_kho is 'Ten kho.';
comment on column public.kiem_kho.dot_kiem_kho is 'Dot kiem kho â€” phan biet cac lan kiem.';
comment on column public.kiem_kho.ma_nvl is 'Ma NVL = tien to truoc dau _ cua ma quet.';
comment on column public.kiem_kho.ma_sp is 'Ma quet day du (tien to + hau to).';
comment on column public.kiem_kho.ten_sp is 'Ten san pham.';
comment on column public.kiem_kho.loai_sp is 'Loai san pham.';
comment on column public.kiem_kho.ngay_gio_kiem_kho is 'Thoi diem kiem kho.';
comment on column public.kiem_kho.nguoi_kiem_kho is 'Nguoi thuc hien kiem kho.';
comment on column public.kiem_kho.thoi_gian_xac_nhan is 'Thoi diem xac nhan kiem ke â€” set khi chot dot (tab Danh sach chi tiet).';
-- Báº£ng tá»•ng há»£p káº¿t quáº£ chá»‘t kiá»ƒm kho â€” DB phiáº¿u cÃ¢n (njdlkyxdieefeebcyaov)
-- Cháº¡y an toÃ n trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/njdlkyxdieefeebcyaov/sql/new
--
-- Má»—i dÃ²ng = 1 sáº£n pháº©m (theo mÃ£ NVL, khÃ´ng phÃ¢n biá»‡t háº­u tá»‘) Ä‘Ã£ gá»™p sá»‘ lÆ°á»£ng
-- khi chá»‘t má»™t Ä‘á»£t kiá»ƒm kho (xem báº£ng chi tiáº¿t public.kiem_kho).

create table if not exists public.kiem_kho_tong_hop (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  dot_kiem_kho text not null,
  ma_nvl text not null,
  ten_sp text,
  loai_sp text,
  tong_so_luong numeric not null default 0,
  chot_luc timestamptz not null default now(),
  nguoi_chot text
);

alter table public.kiem_kho_tong_hop
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists dot_kiem_kho text,
  add column if not exists ma_nvl text,
  add column if not exists ten_sp text,
  add column if not exists loai_sp text,
  add column if not exists tong_so_luong numeric not null default 0,
  add column if not exists chot_luc timestamptz not null default now(),
  add column if not exists nguoi_chot text;

create index if not exists kiem_kho_tong_hop_dot_idx on public.kiem_kho_tong_hop (dot_kiem_kho);
create index if not exists kiem_kho_tong_hop_ma_nvl_idx on public.kiem_kho_tong_hop (ma_nvl);
create unique index if not exists kiem_kho_tong_hop_dot_ma_nvl_uidx
  on public.kiem_kho_tong_hop (dot_kiem_kho, ma_nvl);

alter table public.kiem_kho_tong_hop enable row level security;

drop policy if exists "kiem_kho_tong_hop_select_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_select_all"
  on public.kiem_kho_tong_hop for select
  using (true);

drop policy if exists "kiem_kho_tong_hop_insert_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_insert_all"
  on public.kiem_kho_tong_hop for insert
  with check (true);

drop policy if exists "kiem_kho_tong_hop_update_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_update_all"
  on public.kiem_kho_tong_hop for update
  using (true)
  with check (true);

drop policy if exists "kiem_kho_tong_hop_delete_all" on public.kiem_kho_tong_hop;
create policy "kiem_kho_tong_hop_delete_all"
  on public.kiem_kho_tong_hop for delete
  using (true);

grant select, insert, update, delete on table public.kiem_kho_tong_hop to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.kiem_kho_tong_hop is 'Ket qua chot kiem cua tung dot â€” gop theo ma NVL (bo hau to), tong so luong.';
comment on column public.kiem_kho_tong_hop.dot_kiem_kho is 'Dot kiem kho â€” khop voi cot dot_kiem_kho cua bang public.kiem_kho.';
comment on column public.kiem_kho_tong_hop.ma_nvl is 'Ma NVL (tien to truoc dau _), khong phan biet hau to.';
comment on column public.kiem_kho_tong_hop.ten_sp is 'Ten san pham.';
comment on column public.kiem_kho_tong_hop.loai_sp is 'Loai san pham.';
comment on column public.kiem_kho_tong_hop.tong_so_luong is 'Tong so dong da quet cua ma NVL nay trong dot.';
comment on column public.kiem_kho_tong_hop.chot_luc is 'Thoi diem chot dot.';
comment on column public.kiem_kho_tong_hop.nguoi_chot is 'Nguoi thuc hien chot dot.';
-- RPC gá»™p/chá»‘t kiá»ƒm kho â€” cháº¡y trong Postgres thay vÃ¬ kÃ©o dá»¯ liá»‡u thÃ´ vá» Node.
-- Cháº¡y an toÃ n trong Supabase SQL Editor (DB "kiem-kho", project grlcgkzotqishzxwpddc):
-- https://supabase.com/dashboard/project/grlcgkzotqishzxwpddc/sql/new
--
-- YÃªu cáº§u: Ä‘Ã£ cháº¡y supabase-kiem-kho.sql vÃ  supabase-kiem-kho-tong-hop.sql trÆ°á»›c.

-- Gá»™p cÃ¡c dÃ²ng kiem_kho cá»§a 1 Ä‘á»£t theo mÃ£ NVL. DÃ¹ng cho:
--  (1) xem trÆ°á»›c tá»•ng há»£p cá»§a Ä‘á»£t CHÆ¯A chá»‘t (chá»‰ Ä‘á»c, khÃ´ng ghi gÃ¬);
--  (2) lÃ m nguá»“n dá»¯ liá»‡u bÃªn trong kiem_kho_chot_dot() khi chá»‘t Ä‘á»£t.
create or replace function public.kiem_kho_gop_theo_ma_nvl(p_dot text)
returns table (
  ma_nvl text,
  ten_sp text,
  loai_sp text,
  tong_so_luong bigint
)
language sql
stable
as $$
  select
    coalesce(nullif(trim(k.ma_nvl), ''), '(khÃ´ng xÃ¡c Ä‘á»‹nh)') as ma_nvl,
    max(k.ten_sp) filter (where k.ten_sp is not null) as ten_sp,
    max(k.loai_sp) filter (where k.loai_sp is not null) as loai_sp,
    count(*)::bigint as tong_so_luong
  from public.kiem_kho k
  where k.dot_kiem_kho = p_dot
  group by 1;
$$;

-- Chá»‘t Ä‘á»£t: set thoi_gian_xac_nhan cho má»i dÃ²ng chi tiáº¿t + gá»™p + upsert
-- kiem_kho_tong_hop, táº¥t cáº£ trong CÃ™NG 1 transaction / 1 round-trip DB.
-- Thay cho cÃ¡ch cÅ©: Node select(limit 20000) rá»“i group báº±ng JS rá»“i upsert.
create or replace function public.kiem_kho_chot_dot(p_dot text, p_nguoi text)
returns setof public.kiem_kho_tong_hop
language plpgsql
as $$
declare
  v_confirmed_at timestamptz := now();
begin
  if not exists (select 1 from public.kiem_kho where dot_kiem_kho = p_dot) then
    raise exception 'DOT_NOT_FOUND';
  end if;

  if not exists (
    select 1 from public.kiem_kho
    where dot_kiem_kho = p_dot and thoi_gian_xac_nhan is null
  ) then
    raise exception 'ALREADY_CONFIRMED';
  end if;

  update public.kiem_kho
  set thoi_gian_xac_nhan = v_confirmed_at
  where dot_kiem_kho = p_dot;

  insert into public.kiem_kho_tong_hop as t
    (dot_kiem_kho, ma_nvl, ten_sp, loai_sp, tong_so_luong, chot_luc, nguoi_chot)
  select p_dot, g.ma_nvl, g.ten_sp, g.loai_sp, g.tong_so_luong, v_confirmed_at, p_nguoi
  from public.kiem_kho_gop_theo_ma_nvl(p_dot) g
  on conflict (dot_kiem_kho, ma_nvl) do update set
    ten_sp = excluded.ten_sp,
    loai_sp = excluded.loai_sp,
    tong_so_luong = excluded.tong_so_luong,
    chot_luc = excluded.chot_luc,
    nguoi_chot = excluded.nguoi_chot;

  return query
    select * from public.kiem_kho_tong_hop where dot_kiem_kho = p_dot;
end;
$$;

grant execute on function public.kiem_kho_gop_theo_ma_nvl(text) to anon, authenticated, service_role;
grant execute on function public.kiem_kho_chot_dot(text, text) to anon, authenticated, service_role;

comment on function public.kiem_kho_gop_theo_ma_nvl(text) is
  'Gop cac dong kiem_kho cua 1 dot theo ma_nvl (GROUP BY trong Postgres). Dung cho xem truoc dot chua chot va ben trong kiem_kho_chot_dot().';
comment on function public.kiem_kho_chot_dot(text, text) is
  'Chot 1 dot kiem kho: set thoi_gian_xac_nhan + gop + upsert kiem_kho_tong_hop trong 1 transaction. Loi: DOT_NOT_FOUND, ALREADY_CONFIRMED.';
-- Báº£ng ghi láº¡i cÃ¡c láº§n Ä‘Ã£ xá»­ lÃ½ (táº¡o phiáº¿u Ä‘iá»u chá»‰nh) cho má»™t dÃ²ng chÃªnh lá»‡ch
-- kiá»ƒm kÃª â€” DB "kiem-kho" (project grlcgkzotqishzxwpddc), cÃ¹ng chá»— vá»›i
-- public.kiem_kho_tong_hop.
-- Cháº¡y an toÃ n trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/grlcgkzotqishzxwpddc/sql/new
--
-- Má»—i dÃ²ng = 1 láº§n táº¡o phiáº¿u nháº­p/xuáº¥t Ä‘iá»u chá»‰nh tá»“n kho cho 1 mÃ£ sáº£n pháº©m
-- nguyÃªn báº£n, giá»¯ Ä‘áº§y Ä‘á»§ háº­u tá»‘ lÃ´/serial sau dáº¥u _ náº¿u cÃ³.
-- cá»§a 1 Ä‘á»£t kiá»ƒm kho, sau khi Ä‘á»‘i chiáº¿u sá»‘ kiá»ƒm kÃª (kiem_kho_tong_hop) vá»›i
-- tá»“n cuá»‘i ká»³ sá»• sÃ¡ch cá»§a thÃ nh pháº©m (RPC ton_kho_san_pham_gop á»Ÿ DB chÃ­nh).
-- DÃ¹ng Ä‘á»ƒ mÃ n "Xá»­ lÃ½ chÃªnh lá»‡ch" biáº¿t dÃ²ng nÃ o Ä‘Ã£ xá»­ lÃ½ mÃ  khÃ´ng pháº£i tÃ­nh láº¡i.

create table if not exists public.kiem_kho_chenh_lech_xu_ly (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  dot_kiem_kho text not null,
  ma_sp text not null,
  loai_phieu text,
  so_luong_dieu_chinh numeric,
  ma_phieu_dieu_chinh text,
  ghi_chu text,
  nguoi_xu_ly text,
  xu_ly_luc timestamptz not null default now()
);

-- Náº¿u mÃ´i trÆ°á»ng cÅ© Ä‘Ã£ tá»«ng táº¡o cá»™t ma_nvl, Ä‘á»•i tÃªn cá»™t Ä‘Ã³ sang ma_sp.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'kiem_kho_chenh_lech_xu_ly'
      and column_name = 'ma_nvl'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'kiem_kho_chenh_lech_xu_ly'
      and column_name = 'ma_sp'
  ) then
    alter table public.kiem_kho_chenh_lech_xu_ly rename column ma_nvl to ma_sp;
  end if;
end $$;

alter table public.kiem_kho_chenh_lech_xu_ly
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists dot_kiem_kho text,
  add column if not exists ma_sp text,
  add column if not exists loai_phieu text,
  add column if not exists so_luong_dieu_chinh numeric,
  add column if not exists ma_phieu_dieu_chinh text,
  add column if not exists ghi_chu text,
  add column if not exists nguoi_xu_ly text,
  add column if not exists xu_ly_luc timestamptz not null default now();

-- TrÆ°á»ng nÃ y tá»«ng dÃ¹ng Ä‘á»ƒ phÃ¢n biá»‡t NVL/thÃ nh pháº©m. Luá»“ng hiá»‡n táº¡i chá»‰ xá»­ lÃ½
-- sáº£n pháº©m nÃªn khÃ´ng cáº§n lÆ°u má»™t giÃ¡ trá»‹ cá»‘ Ä‘á»‹nh ná»¯a.
alter table public.kiem_kho_chenh_lech_xu_ly
  drop column if exists loai_kho;

create index if not exists kiem_kho_chenh_lech_xu_ly_dot_idx
  on public.kiem_kho_chenh_lech_xu_ly (dot_kiem_kho);
drop index if exists public.kiem_kho_chenh_lech_xu_ly_dot_ma_nvl_idx;
create index if not exists kiem_kho_chenh_lech_xu_ly_dot_ma_sp_idx
  on public.kiem_kho_chenh_lech_xu_ly (dot_kiem_kho, ma_sp);

alter table public.kiem_kho_chenh_lech_xu_ly enable row level security;

drop policy if exists "kiem_kho_chenh_lech_xu_ly_select_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_select_all"
  on public.kiem_kho_chenh_lech_xu_ly for select
  using (true);

drop policy if exists "kiem_kho_chenh_lech_xu_ly_insert_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_insert_all"
  on public.kiem_kho_chenh_lech_xu_ly for insert
  with check (true);

drop policy if exists "kiem_kho_chenh_lech_xu_ly_update_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_update_all"
  on public.kiem_kho_chenh_lech_xu_ly for update
  using (true)
  with check (true);

drop policy if exists "kiem_kho_chenh_lech_xu_ly_delete_all" on public.kiem_kho_chenh_lech_xu_ly;
create policy "kiem_kho_chenh_lech_xu_ly_delete_all"
  on public.kiem_kho_chenh_lech_xu_ly for delete
  using (true);

grant select, insert, update, delete on table public.kiem_kho_chenh_lech_xu_ly to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.kiem_kho_chenh_lech_xu_ly is
  'Lich su tao phieu dieu chinh ton kho cho tung dong chenh lech kiem ke (man Xu ly chenh lech).';
comment on column public.kiem_kho_chenh_lech_xu_ly.dot_kiem_kho is 'Dot kiem kho â€” khop cot dot_kiem_kho cua public.kiem_kho.';
comment on column public.kiem_kho_chenh_lech_xu_ly.ma_sp is 'Ma san pham nguyen ban, giu day du hau to lo/serial neu co.';
comment on column public.kiem_kho_chenh_lech_xu_ly.loai_phieu is 'nhap hoac xuat â€” loai phieu dieu chinh da tao.';
comment on column public.kiem_kho_chenh_lech_xu_ly.so_luong_dieu_chinh is 'So luong da dieu chinh (tri tuyet doi cua chenh lech tai thoi diem xu ly).';
comment on column public.kiem_kho_chenh_lech_xu_ly.ma_phieu_dieu_chinh is 'Ma phieu tao o public.phieu_xuat_nhap_kho (DB chinh).';
comment on column public.kiem_kho_chenh_lech_xu_ly.nguoi_xu_ly is 'Nguoi bam tao phieu dieu chinh.';
comment on column public.kiem_kho_chenh_lech_xu_ly.xu_ly_luc is 'Thoi diem tao phieu dieu chinh.';
