-- Bảng đối soát (quét QR gọn) — DB cân tự động / phiếu cân
-- Project: njdlkyxdieefeebcyaov
-- Chạy trong Supabase SQL Editor:
-- https://supabase.com/dashboard/project/njdlkyxdieefeebcyaov/sql/new

create table if not exists public.doi_soat (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ten_kho text,
  dot_doi_soat text,
  ma_nvl text,
  ma_sp text,
  ten_sp text,
  loai_sp text,
  ngay_gio_doi_soat timestamptz not null default now(),
  nguoi_doi_soat text
);

alter table public.doi_soat
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists ten_kho text,
  add column if not exists dot_doi_soat text,
  add column if not exists ma_nvl text,
  add column if not exists ma_sp text,
  add column if not exists ten_sp text,
  add column if not exists loai_sp text,
  add column if not exists ngay_gio_doi_soat timestamptz not null default now(),
  add column if not exists nguoi_doi_soat text;

create index if not exists doi_soat_ngay_gio_idx on public.doi_soat (ngay_gio_doi_soat desc);
create index if not exists doi_soat_ma_sp_idx on public.doi_soat (ma_sp);
create index if not exists doi_soat_ma_nvl_idx on public.doi_soat (ma_nvl);
create index if not exists doi_soat_ten_kho_idx on public.doi_soat (ten_kho);
create index if not exists doi_soat_dot_doi_soat_idx on public.doi_soat (dot_doi_soat);

alter table public.doi_soat enable row level security;

drop policy if exists "doi_soat_select_all" on public.doi_soat;
create policy "doi_soat_select_all"
  on public.doi_soat for select
  using (true);

drop policy if exists "doi_soat_insert_all" on public.doi_soat;
create policy "doi_soat_insert_all"
  on public.doi_soat for insert
  with check (true);

drop policy if exists "doi_soat_update_all" on public.doi_soat;
create policy "doi_soat_update_all"
  on public.doi_soat for update
  using (true)
  with check (true);

drop policy if exists "doi_soat_delete_all" on public.doi_soat;
create policy "doi_soat_delete_all"
  on public.doi_soat for delete
  using (true);

grant select, insert, update, delete on table public.doi_soat to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

comment on table public.doi_soat is 'Dong doi soat quet QR theo dot / kho.';
comment on column public.doi_soat.ten_kho is 'Ten kho.';
comment on column public.doi_soat.dot_doi_soat is 'Dot doi soat — phan biet cac lan quet.';
comment on column public.doi_soat.ma_nvl is 'Ma NVL = tien to truoc dau _ cua ma quet.';
comment on column public.doi_soat.ma_sp is 'Ma quet day du (tien to + hau to).';
comment on column public.doi_soat.ten_sp is 'Ten san pham.';
comment on column public.doi_soat.loai_sp is 'Loai san pham.';
comment on column public.doi_soat.ngay_gio_doi_soat is 'Thoi diem doi soat.';
comment on column public.doi_soat.nguoi_doi_soat is 'Nguoi thuc hien doi soat.';
