-- Bảng đơn hàng (thiếu file create gốc trong repo — bổ sung cho full bootstrap)

create table if not exists public.don_hang (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ma_don_hang text,
  loai_don_hang text default '',
  trang_thai text default 'Chờ sx',
  nhan_vien text default '',
  khach_hang text default '',
  san_pham jsonb not null default '[]'::jsonb,
  ghi_chu text default '',
  so_luong numeric,
  so_luong_ton numeric,
  lenh_sx text default ''
);

create unique index if not exists don_hang_ma_don_hang_uidx
  on public.don_hang (ma_don_hang)
  where ma_don_hang is not null and trim(ma_don_hang) <> '';

alter table public.don_hang enable row level security;

drop policy if exists "don_hang_select_all" on public.don_hang;
create policy "don_hang_select_all" on public.don_hang for select using (true);
drop policy if exists "don_hang_insert_all" on public.don_hang;
create policy "don_hang_insert_all" on public.don_hang for insert with check (true);
drop policy if exists "don_hang_update_all" on public.don_hang;
create policy "don_hang_update_all" on public.don_hang for update using (true) with check (true);
drop policy if exists "don_hang_delete_all" on public.don_hang;
create policy "don_hang_delete_all" on public.don_hang for delete using (true);
