-- Bảng phân công công việc
-- Chạy an toàn nhiều lần trong Supabase SQL Editor.

create table if not exists public.phan_cong_cv (
  id bigint generated by default as identity primary key,
  ngay date,
  ca text,
  cong_viec text,
  nhan_su_phu_trach text,
  ghi_chu text,
  thanh_pham text,
  "dm_thanh_pham_TT" text
);

alter table public.phan_cong_cv enable row level security;

drop policy if exists "phan_cong_cv_select_all" on public.phan_cong_cv;
create policy "phan_cong_cv_select_all"
  on public.phan_cong_cv for select using (true);

drop policy if exists "phan_cong_cv_insert_all" on public.phan_cong_cv;
create policy "phan_cong_cv_insert_all"
  on public.phan_cong_cv for insert with check (true);

drop policy if exists "phan_cong_cv_update_all" on public.phan_cong_cv;
create policy "phan_cong_cv_update_all"
  on public.phan_cong_cv for update using (true) with check (true);

drop policy if exists "phan_cong_cv_delete_all" on public.phan_cong_cv;
create policy "phan_cong_cv_delete_all"
  on public.phan_cong_cv for delete using (true);

create index if not exists phan_cong_cv_ngay_idx
  on public.phan_cong_cv (ngay desc);

comment on table public.phan_cong_cv is 'Danh sach phan cong cong viec.';
